import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Theme from "../utils/theme";
import Header from "../components/header";
import Footer from "../components/footer";

import { AuthContext, AuthProvider } from "../providers/auth";
import { useContext } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
  noAuth
}: Readonly<{
  children: React.ReactNode;
  auth?: React.ReactNode;
  noAuth?: React.ReactNode;
}>) {

  
  
  return (
    <html lang="en">
      <head>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Theme>
          <AuthProvider authHeader={auth} noAuthHeader={noAuth}>
            <div className="main-container">
              <div className="content-container">
                {children}
              </div>
            </div>
            <Footer />
          </AuthProvider>
        </Theme>
      </body>
    </html>
  );
}
